export const LOAD_REQUESTS_TRIGGER = 'LOAD_REQUESTS_TRIGGER';
export const UPDATE_REQUESTS = 'UPDATE_REQUESTS';
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export const CHANGE_SAVING_STATUS = 'CHANGE_SAVING_STATUS';
export const NEW_REQUEST = 'NEW_REQUEST';